export default [
    {
        value:"wooden",
        labelOption:"Wooden"
    },
    {
        value:"forest",
        labelOption:"Forest"
    },
    {
        value:"sweets",
        labelOption:"Sweets"
    },
    {
        value:"bubbles",
        labelOption:"Bubbles"
    },
    {
        value:"crackle",
        labelOption:"Crackle"
    },
    {
        value:"sparkle",
        labelOption:"Sparkle"
    },
    {
        value:"rainbow",
        labelOption:"Rainbow"
    },
    {
        value:"smoke",
        labelOption:"Smoke"
    },
    {
        value:"nightsky",
        labelOption:"Nightsky"
    },
    {
        value:"sunset",
        labelOption:"Sunset"
    }
]