export default [
    {
        value:"snow",
        labelOption:"Snow"
    },
    {
        value:"blood",
        labelOption:"Blood"
    },
    {
        value:"slime",
        labelOption:"Slime"
    },
    {
        value:"gloom",
        labelOption:"Gloom"
    },
    {
        value:"candy",
        labelOption:"Candy"
    },
    {
        value:"purple",
        labelOption:"Purple"
    },
    {
        value:"blue",
        labelOption:"Blue"
    },
    {
        value:"olive",
        labelOption:"Olive"
    },
    {
        value:"royal",
        labelOption:"Royal"
    },
    {
        value:"lilac",
        labelOption:"Lilac"
    }
]