export default [
    {
        value:"-",
        labelOption:"-"
    },{
        value:"nature",
        labelOption:"Nature"
    },
    {
        value:"monochromatic",
        labelOption:"Monochromatic"
    },
    {
        value:"wallpapers",
        labelOption:"Wallpapers"
    },
    {
        value:"3d-renders",
        labelOption:"3d-renders"
    },
    {
        value:"textures-patterns",
        labelOption:"Textures Patterns"
    },
    {
        value:"street-photography",
        labelOption:"Street Photography"
    },
    {
        value:"experimental",
        labelOption:"Experimental"
    },
    {
        value:"film",
        labelOption:"Film"
    },
    {
        value:"animals",
        labelOption:"Animals"
    },
    {
        value:"travel",
        labelOption:"Travel"
    },
    {
        value:"people",
        labelOption:"People"
    },
    {
        value:"spirituality",
        labelOption:"Spirituality"
    },
    {
        value:"sports",
        labelOption:"Sports"
    },
    {
        value:"arts-culture",
        labelOption:"Arts-culture"
    }
]