export default [
    {
        value:"01cm",
        labelOption:"0.1cm"
    },
    {
        value:"02cm",
        labelOption:"0.2cm"
    },
    {
        value:"03cm",
        labelOption:"0.3cm"
    },
    {
        value:"04cm",
        labelOption:"0.4cm"
    },
    {
        value:"05cm",
        labelOption:"0.5cm"
    }
]